### ISSUE TITLE
Error, after starting vm - VT-x is not available. (VERR_VMX_NO_VMX)

### ISSUE THREAD

**Issue by dmarynych** [xdissent/ievms#126]
Error, i've met, is surely not frequent, but who knows - maybe you can fix it simply :)
My floopy disk is broken, and while installation process, script probably enables it for new vm.
Then it gives much of this errors:
`VBoxManage: error: Machine "IE8 - WinXP" is not running (currently powered off)!`
and installations doesn't go on.

When i trying to run vm, through virtualbox interface, it says: 
`VT-x is not available. (VERR_VMX_NO_VMX)`

After, i uncheck floopy disk option in vm settings, all works fine.

**Comment by xdissent** [comment]
Latest version requires VirtualBox 5.0. Reopen if this issue persists.
