### ISSUE TITLE
VMs don't work at all on non-VT-x CPUs

### ISSUE THREAD

**Issue by CoJaBo** [xdissent/ievms#138]
The created VM images appear to have VT-x turned on; there is no way to turn this off, as the setting to do so is disabled unless the CPU supports VT-x (this seems like a VBox bug, but it apparently dates back at least 2 years). The command line tool does not appear to work either. There is no way to use the VMs at all, as the setting cannot be turned off by any means I could find; if theres a workaround, I'd love to hear it.

**Comment by xdissent** [comment]
Latest version requires VirtualBox 5.0. Reopen if this issue persists.
