### ISSUE TITLE
[SOLVED] Issue with installing Oracle VM VirtualBox Extension Pack on OSX

### ISSUE THREAD

**Issue by dotnetCarpenter** [xdissent/ievms#148]
I would like, if you could include this in the README:
### Issue with installing Oracle VM VirtualBox Extension Pack on OSX
Oracle VM VirtualBox checks your permissions in /Applications and if they are too permissive, VirtualBox will throw an error. Typically it will look like this:
```bash
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to install "[PATH TO DOWNLOAD DIRECTORY]/.ievms/Oracle_VM_VirtualBox_Extension_Pack-4.2.12.vbox-extpack"
VBoxManage: error: The installer failed with exit code 1: VBoxExtPackHelperApp: error: World writable: '/Applications'
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ExtPackManager, interface IExtPackManager
VBoxManage: error: Context: "int handleExtPack(HandlerArg*)" at line 1112 of file VBoxManageMisc.cpp
```
To restrict your permissions, you simply need to do ``sudo chown root:admin /Applications``and ``sudo chmod -R 755 /Applications``. Now your permissions should be both more secure and Oracle VM VirtualBox will install the *Extension Pack* as well as any Windows VMs via ``curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | IEVMS_VERSIONS="10" bash``

Feel free to edit my text prososal. I just hope it will help others as it has taken me weeks before I spend enough time to figure this out.

**Comment by xdissent** [comment]
Latest version requires VirtualBox 5.0. Reopen if problem persists.

**Comment by Miigaa1191** [comment]
To install extension package, I followed: sudo chown root:admin /Applicationsand sudo chmod -R 755 /Applications. Unfortunately, I couldn't open VM (Error message: VirtualBox quit unexpectedly. How can I redo this code in the command line. Because  my VirtualBox worked before.

**Comment by rollecode** [comment]
I'm on VirtualBox 5.1.22, fresh Mac, still having this issue. Installing the ext pack manually helped.

**Comment by CricketScience** [comment]
I had this issue with 5.1.22 on Mac 10.12.6 but it went away with 5.1.28

**Comment by JurateP** [comment]
Hello, how  do you install it manually? can anyone post the instructions please?

**Comment by JurateP** [comment]
> I would like, if you could include this in the README:
> 
> ### Issue with installing Oracle VM VirtualBox Extension Pack on OSX
> Oracle VM VirtualBox checks your permissions in /Applications and if they are too permissive, VirtualBox will throw an error. Typically it will look like this:
> 
> ```shell
> Progress state: NS_ERROR_FAILURE
> VBoxManage: error: Failed to install "[PATH TO DOWNLOAD DIRECTORY]/.ievms/Oracle_VM_VirtualBox_Extension_Pack-4.2.12.vbox-extpack"
> VBoxManage: error: The installer failed with exit code 1: VBoxExtPackHelperApp: error: World writable: '/Applications'
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ExtPackManager, interface IExtPackManager
> VBoxManage: error: Context: "int handleExtPack(HandlerArg*)" at line 1112 of file VBoxManageMisc.cpp
> ```
> 
> To restrict your permissions, you simply need to do `sudo chown root:admin /Applications`and `sudo chmod -R 755 /Applications`. Now your permissions should be both more secure and Oracle VM VirtualBox will install the _Extension Pack_ as well as any Windows VMs via `curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | IEVMS_VERSIONS="10" bash`
> 
> Feel free to edit my text prososal. I just hope it will help others as it has taken me weeks before I spend enough time to figure this out.

Could you please explain this in English language? "sudo chown root:admin /Applications`and `sudo chmod -R 755 /Applications" Please be so kind to write how to proceed exactly. thank you.
