### ISSUE TITLE
Error VERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Blacksnipe** [xdissent/ievms#150]
Hi,

I'll leave it as simple as the virtual machines boot on my Virtual Box. I keep getting the following error every single time I want to start the VM:

    error VERR_FILE_NOT_FOUND opening image file '/Users/maister/.ievms/IE8 - WinXP-disk1.vmdk' (VERR_FILE_NOT_FOUND).

I've tried reinstalling the one VM, all the VM's and even VirtualBox itself, but nothing solved it, so I'm thinking it's in the code. What do I have to do to fix this?

Thanks.

**Comment by xdissent** [comment]
Sounds like the VM was incorrectly removed.
