### ISSUE TITLE
Revert to clean version of VM with new expiration on license

### ISSUE THREAD

**Issue by bradical** [xdissent/ievms#157]
I saw some mention of doing this in a few issues, but wasn't clear on the process.

I've been:
- Deleting the vm from VirtualBox (including the files)
- Re-running: `curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | IEVMS_VERSIONS="7 9" bash` to reinstall a particular version

Is there an easier (less network intensive way) to reset the VM to a point where the time left on my license starts over or is this as good as it gets?

**Comment by Rodri9o** [comment]
I sent some beer money your way. Thank man!
