### ISSUE TITLE
VBoxManage: error: Cannot find the Guest Additions ISO image

### ISSUE THREAD

**Issue by Nix-id** [xdissent/ievms#163]
```
Building IE9 - Win7 VM
build_ievm_ie9
Found ievms control ISO at /home/mag/.ievms/ievms-control-0.1.0.iso - skipping download
Attaching ievms control ISO
Starting VM IE9 - Win7
Waiting for VM "IE9 - Win7" to power on...
VM "IE9 - Win7" has been successfully started.
Waiting for IE9 - Win7 to shutdown...
Ejecting ievms control ISO
Attaching Guest Additions
VBoxManage: error: Cannot find the Guest Additions ISO image
```

**Comment by robespmun** [comment]
Installing virtualbox-guest-additions-iso didn't work for me. I'm using Ubuntu 16.04 and VirtualVox 5.0.40, I'm still getting the same error.

Successfully imported the appliance.
Adding shared folder
Building IE11 - Win7 VM
build_ievm_ie11
Found ievms control ISO at /home/rob/.ievms/ievms-control-0.3.3.iso - skipping download
MD5 check succeeded for /home/rob/.ievms/ievms-control-0.3.3.iso
Attaching ievms control ISO
Starting VM IE11 - Win7
Waiting for VM "IE11 - Win7" to power on...
VM "IE11 - Win7" has been successfully started.
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...
Ejecting ievms control ISO
Attaching Guest Additions
VBoxManage: error: Cannot find the Guest Additions ISO image

This is happening on the IE11 machine. It worked fine on the EDGE vm that thankfully includes IE11 too.
