### ISSUE TITLE
ie10 no longer installs

### ISSUE THREAD

**Issue by hostyle** [xdissent/ievms#167]
The IE10 / Win 7 virtualbox is running IE9, as is the IE9 / Win 7 virtualbox. So they seem to be essentially the same. This used to work (last time I tried it was probably around March 2013 or so, and I can recall that it installed Windows 8 back then for IE10). I get the following messages during install, which may be related?

<pre>Waiting for IE10 - Win7 to shutdown...
Ejecting ievms control ISO
Attaching Guest Additions
VBoxManage: error: Could not find file for the medium '/media/tbdisk/work/VMs/additions' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, AccessMode_ReadWrite, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 210 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "additions"
</pre>

There is no additions folder in that location, but the iso file does exist in /usr/share/virtualbox/VBoxGuestAdditions.iso - I read in another bug report that the Guest Additions part is optional. so I'm assuming that this is a separate issue ? I tried running ievms again, and it seemed to think that everything was fine.

**Comment by sunruh** [comment]
Fixed this problem on Ubuntu 15.04 by installing `virtualbox-guest-additions-iso`

**Comment by nmrugg** [comment]
I also had to install `virtualbox-guest-additions-iso` on 15.10. That should probably be in the readme.
