### ISSUE TITLE
VBOX_E_FILE_ERROR

### ISSUE THREAD

**Issue by pkc34** [xdissent/ievms#171]
I have gotten ievms to work well on my MacBook, although all three versions only had IE6.  I was eventually able to upgrade one VM to IE7 and one VM to IE8.  On my Mac Mini, however, I have run into problems.  It originally froze on my first attempt (welcome back to Windows!!).  After getting back in, I was not able to get Terminal to complete the process.  I have tried cleaning up the files, although I cannot locate .ievms, but still no success.  What follows is what I receive each time, even if I try installing each VM individually...

----begin snippet----
10: Hard disk image: source image=IE6 - WinXP-disk1.vmdk, target path=/Users/patrickcampbell/.ievms/IE6 - WinXP-disk1.vmdk, controller=8;channel=0
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the clone medium '/Users/patrickcampbell/.ievms/IE6 - WinXP-disk1.vmdk'.
VBoxManage: error: VMDK: could not create new file '/Users/patrickcampbell/.ievms/IE6 - WinXP-disk1.vmdk' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 781 of file VBoxManageAppliance.cpp
----end snippet---

Any insight would be greatly appreciated.  Thank you.

**Comment by xdissent** [comment]
The original issue was that a VM was incorrectly removed and couldn't be reinstalled. Then resuming came up, which will be tracked in #224
