### ISSUE TITLE
Dev Tools disabled IE11 - Win7

### ISSUE THREAD

**Issue by nilpath** [xdissent/ievms#176]
Hi

Is it possible to add a Windows 8 VM for IE11 ? Tried to use the Dev Tools in the current IE11 - Win7 VM and it seems to be disabled for [older](http://msdn.microsoft.com/en-us/library/ie/bg182632.aspx) version of win7. An alternative could be to install windows updates on the win7 machine.

**Comment by xdissent** [comment]
IE11 does get dev tools now, but there is another issue #261
