### ISSUE TITLE
NS_ERROR_FAILURE on import

### ISSUE THREAD

**Issue by grahamsprague** [xdissent/ievms#184]
I get the following error on the import part of the script. I'm using Mac OS 10.8.5 and Virtual Box 4.3.0. I tried uninstalling Virtual box and re-installing. Also tried removing the .ievms directory and I still get the following error on every try.

Progress state: NS_ERROR_FAILURE
VBoxManage: error: Appliance import failed
VBoxManage: error: Medium '/Users/sprgr001/.ievms/IE6 - WinXP-disk1.vmdk' cannot be closed because it is still attached to 1 virtual machines
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component Medium, interface IMedium
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp

**Comment by kimbo6365** [comment]
Yup, I was also having this problem, which boiled down to a permissions issue. I had initially installed VirtualBox under a different user account on my machine, so I had to change the Default Machine Folder in VirtualBox's preferences to the current user account. Smooth sailing after that.

**Comment by kelicia** [comment]
Thank you @kimbo6365 and @nragaz! That was just the clue I needed to get this straightened out!
