### ISSUE TITLE
IE9 Download timeout issues

### ISSUE THREAD

**Issue by FStop** [xdissent/ievms#189]
Mac OS 10.8.5

I keep getting a timeout issue when the IE9 VM reaches 707.1 MB. The download speed goes to 0, and my network connection stops working until I reset it. I've tried both ethernet and WiFi, which are on different networks.

I am currently downloading with no issues directly from http://www.modern.ie/en-us/virtualization-tools#downloads using their CURL command: `curl -O "https://az412801.vo.msecnd.net/vhd/IEKitV1_Final/VirtualBox/OSX/IE9_Win7/IE9.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar,5.rar}"`

**Comment by xavierartot** [comment]
me too

**Comment by scifisamurai** [comment]
Same issue here on Yosemite - hangs at 674 MB on OS X when trying to download http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE9_Win7.zip via curl

**Comment by xdissent** [comment]
Don't know what could be going wrong other than weird network errors. Reopen if this is still happening with the latest version - I know MS has altered their server configuration since this issue was reported.
