### ISSUE TITLE
IE11 on Windows 8.1?

### ISSUE THREAD

**Issue by chitsaou** [xdissent/ievms#193]
I noticed that IE11 for Windows 8.1 is now available at [modern.IE website](http://loc.modern.ie/virtualization-tools#downloads). I didn't see this few days ago, so I believe this is a new one. Does this make it possible to use IE11 without reuse Win7?

**Comment by elsigh** [comment]
![image](https://cloud.githubusercontent.com/assets/517210/8311565/e7138224-198b-11e5-9f47-5504aba23e6c.png)

Looks like this is there now.

**Comment by chitsaou** [comment]
Microsoft is now officially providing IE11 on Windows 8.1 and Edge on Windows 10 images.  Close This.
