### ISSUE TITLE
IE10 VM uses Win7

### ISSUE THREAD

**Issue by grayghostvisuals** [xdissent/ievms#197]
Wondering what the reason is for IE10 using Win7 when running the following curl command:

```bash
curl -s https://raw.github.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="10" bash
```

**Comment by xdissent** [comment]
Thank you for the input. I'm going to close this because I'm pretty sure we'll include a couple more VMs from MS in the near future and will have to rewrite that section anyway.
