### ISSUE TITLE
Windows 7 VMs get stuck installing Virtualbox Guest Additions

### ISSUE THREAD

**Issue by savingschampion** [xdissent/ievms#207]
Running through an installation today on virtualbox 4.3.8, I noticed that IE9 was taking forever to create.

I looked via the Virtualbox GUI and saw that there was a dialog that was asking about Hardware driver signing with a "Your computer must restart to apply changes" dialog over the top. What i'm guessing happened is that the dialog appears over the top and gets in the way of the scripted install.

**Comment by servel333** [comment]
* Run `VBoxManage list hdds`
* Check the `State:` field for `inaccessible` for disks you've deleted.
* Look at the `Location:` column and confirm that is the disk you expect to be deleted
* Look at the `UUID:` field and copy the uuid.
* Type `VBoxManage closemedium disk $(uuid)`

```
VBoxManage list hdds
# UUID:           01d5ccb5-2319-4e9c-bd76-daaaceffce53
# Parent UUID:    base
# State:          inaccessible
# Type:           normal (base)
# Location:       /Users/nperry/.ievms/IE6 - WinXP-disk1.vmdk
# Storage format: VMDK
# Capacity:       129948 MBytes
VBoxManage closemedium disk 01d5ccb5-2319-4e9c-bd76-daaaceffce53
```

**Comment by xdissent** [comment]
Latest version requires VirtualBox 5.0, which should certainly fix this.
