### ISSUE TITLE
bash: line 10: syntax error near unexpected token `A'

### ISSUE THREAD

**Issue by kamal2222ahmed** [xdissent/ievms#208]
I tried to install ievms on centos 6.4 after modifying for unar to 7za, as

check_unar() {
    if [ "${kernel}" == "Darwin" ]
    then
        hash unar 2>&- || install_unar
    else
        #hash unar 2>&- || fail "Linux support requires unar (sudo apt-get install for Ubuntu/Debian)"
        echo "using 7za . . . "
    fi
}

and 

 download "OVA ZIP" "${url}" "${archive}"

        log "Extracting OVA from ${ievms_home}/${archive}"
        #unar "${archive}" || fail "Failed to extract ${archive} to ${ievms_home}/${ova}, unar command returned error code $?"
        7za "${archive}" || fail "Failed to extract ${archive} to ${ievms_home}/${ova}, 7za command returned error code $?"
    fi
, but now when i run ievms.sh

 
  ./ievms.sh | IEVMS_VERSIONS="8" bash
bash: line 1: Checking: command not found
bash: line 2: Checking: command not found
bash: line 3: Pack: command not found
bash: line 4: using: command not found
bash: line 5: Building: command not found
bash: line 6: Checking: command not found
bash: line 7: Downloading: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  716M  100  716M    0     0  10.8M      0  0:01:06  0:01:06 --:--:-- 9603k
bash: line 8: Extracting: command not found
bash: line 10: syntax error near unexpected token `A'
bash: line 10: `7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18'

**Comment by xdissent** [comment]
Looks like 7za is printing its help message? Perhaps you have the wrong options. We don't support 7za though so you're on your own unfortunately.
