### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by francescom** [xdissent/ievms#217]
Hi, thanks for this incredible script. I have been using VMs installed years ago for a long time. Today I tried reinstalling them with mixed results.

First there must be some naming problem, often the source image file is different from the path filename (on all or most VMs):

```
Hard disk image: source image=IE9 - Win7-disk1.vmdk, target path=/Users/fmm/.ievms/IE11 - Win7-disk1.vmdk, controller=10;channel=0
```

Then it has problems detecting the shutdown:

```
...
Waiting for IE11 - Win7 to shutdown...
...
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...

(forever)
```
But I heard a chime so it might have already shut down.

One more problem is that I can't seem to be able to installe IE9 - Win7:

```
11: Hard disk image: source image=IE9 - Win7-disk1.vmdk, target path=/Users/fmm/.ievms/IE9 - Win7-disk1.vmdk, controller=10;channel=0
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
Progress state: NS_ERROR_INVALID_ARG
VBoxManage: error: Appliance import failed
VBoxManage: error: Cannot register the hard disk '/Users/fmm/.ievms/IE9 - Win7-disk1.vmdk' {d624a0a9-e52c-4126-8017-bc3d4452047e} because a hard disk '/Users/fmm/.ievms/IE9 - Win7-disk1.vmdk' with UUID {b941eeaa-c719-44e1-b75a-7f3250c1088a} already exists
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp
```

(removing IE9 - Win7-disk1.vmdk is of no help)

**Comment by servel333** [comment]
I am running VirtualBox 4.3.20 and this solved my issue:

* Run `VBoxManage list hdds`
* Check the `State:` field for `inaccessible` for disks you've deleted.
* Look at the `Location:` column and confirm that is the disk you expect to be deleted
* Look at the `UUID:` field and copy the uuid.
* Type `VBoxManage closemedium disk $(uuid)`

```
VBoxManage list hdds
# UUID:           01d5ccb5-2319-4e9c-bd76-daaaceffce53
# Parent UUID:    base
# State:          inaccessible
# Type:           normal (base)
# Location:       /Users/nperry/.ievms/IE6 - WinXP-disk1.vmdk
# Storage format: VMDK
# Capacity:       129948 MBytes
VBoxManage closemedium disk 01d5ccb5-2319-4e9c-bd76-daaaceffce53
```

**Comment by vladat** [comment]
Thanks @servel333, it solved the problem I've had.

**Comment by anotherjames** [comment]
The solution provided by @servel333 was exactly what I needed (as well as to delete the download itself under ~/.ievms/ ). I'd hit the issue because I had removed the VM from VirtualBox without deleting all files, so it remained in that inaccessible state despite not being listed in the UI.

**Comment by xdissent** [comment]
You can also remove the inaccessible media from VirtualBox with File -> Virtual Media Manager.
