### ISSUE TITLE
Installation of Oracle VM Virtualbox 4.3.10 for Windows 7 (64 bit)

### ISSUE THREAD

**Issue by ghost** [xdissent/ievms#221]
I have tried to install Oracle VM Virtualbox 4.3.10 for Windows 7 (64 bit). At the end of Installation process ther appears the warning message 
"
Warning: Network Interfaces

Installing the Oracle Vm Virtualbox 4.3.10 Networking Feature will reset your network connection and temporarily disconnect you from the Network.
Proceed with Installation now ?
"
Does this Installation procedure damage the previous Network Settings ( for example WLAN) ?
Does anyone offer an detailled Installation guidance ?
Thank you

**Comment by xdissent** [comment]
We don't explicitly support Windows (although I've seen a fork or two). Either way, sounds like an issue with VirtualBox itself, and I don't know enough about windows to advise.
