### ISSUE TITLE
Win XP keep asking for activation

### ISSUE THREAD

**Issue by rizkysyazuli** [xdissent/ievms#225]
it's been a while since i last run the VMs. so it's natural that it started asking for activation (the Win XP for IE 6, 7, 8). but after i reset them to the "clean" snapshot, it still prompting for activation.

any ideas? am i asking to the wrong place?

**Comment by tnguyen14** [comment]
Wondering if anyone has a good solution to this issue? I have reverted back to the clean state, but still am unable to log in or use the machine.

**Comment by joeguilmette** [comment]
Same issue.

**Comment by quarklemotion** [comment]
I had the same issue, just removed the XP VM in virtualbox, selected 'delete all files', then rebuilt (just) the win XP IE8 VM using:

`curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="8" bash`

**Comment by xdissent** [comment]
Thems the breaks, unfortunately. The XP image expires after 30-days, and reverting to clean will not help. Sorry
