### ISSUE TITLE
Can this be used on a windows based system that has curl available?

### ISSUE THREAD

**Issue by seiyria** [xdissent/ievms#229]
For example, we have the `curl` utility via git bash, but we don't have `unar`, for example. This would greatly help us at work.

**Comment by StormPooper** [comment]
Update to this: I've gotten it mostly working with Windows, but there are a couple of small issues. I plan on making a pull request when i get it fully working, I'll update here when i do.

**Comment by seiyria** [comment]
Thank you @StormPooper!

**Comment by StormPooper** [comment]
@seiyria I've got it working on my machine, if you want to try it out [here](https://github.com/StormPooper/ievms).

Replace the script url in the readme with `https://raw.githubusercontent.com/StormPooper/ievms/master/ievms.sh` in any commands you're running and you should be good to go.

Let me know if it works for you and I'll submit a pull request to merge it in here.

**Comment by seiyria** [comment]
Hm, just using regular git bash, it tells me that it can't find curl, despite the fact that I used curl to download the script. Perhaps it's looking on my path, though, which wouldn't work. I only have it installed because of git bash.

**Comment by StormPooper** [comment]
@seiyria yes, it looks in your PATH for the executables. I'm using Git on mine too and it's working. 

If you can remember, which of these did you select during installation? You need to select the second or third so it will place them on PATH for you. 
![image](https://cloud.githubusercontent.com/assets/1657182/6186942/5794f28c-b378-11e4-83e7-d506662c3bdc.png)

You can try reinstalling and selecting the second option (which is what I use), or just adding your `Git\bin\` folder to PATH.

**Comment by StormPooper** [comment]
@seiyria any luck in getting it to work?

**Comment by smithk58** [comment]
@StormPooper - I installed Git with the third option and Git is on my path. If I run ievms.sh it says it can't find curl.

**Comment by StormPooper** [comment]
@smithk58 can you raise an issue [here](https://github.com/StormPooper/ievms) with what you've tried and what error you get, etc?

**Comment by StormPooper** [comment]
@seiyria @smithk58 can you please try downloading the script and running again? I've fixed an error in the check for curl.

**Comment by seiyria** [comment]
@StormPooper we kinda got slammed with things to do at work, so we'll try again when we can.

**Comment by xdissent** [comment]
Moving this to #80. Thanks for the effort @StormPooper ! Let me know (in #80) the latest status if you get a chance

**Comment by fselem** [comment]
Im gay
