### ISSUE TITLE
IE11 Image contains IE9 not IE11

### ISSUE THREAD

**Issue by ajbeach2** [xdissent/ievms#235]
I initially installed all of the vms for all versions of IE.

curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="11" bash
Checking for VirtualBox
Checking for Oracle VM VirtualBox Extension Pack
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Building IE11 VM
Checking for existing OVA at /Users/alexbeach/.ievms/IE9 - Win7.ova
Checking for existing IE11 - Win7 VM
Done!

I need to use IE11 but for some reason this is using IE9. When I boot up that Ie11 vm it is running ie9

**Comment by xdissent** [comment]
It should run the installer automatically when it says "Installing IE". In fact, the shutdown that follows is initiated by the IE11 installer when it completes. So I have no idea what happened. There is a change in the latest version that should make the IE installation process more reliable. Please reopen if you're still experiencing this issue with the latest version.
