### ISSUE TITLE
Microsoft provides Vagrant images

### ISSUE THREAD

**Issue by kwbr** [xdissent/ievms#239]
Seems Microsoft now provides Vagrant boxes for Modern.IE images
http://blog.syntaxc4.net/post/2014/09/03/windows-boxes-for-vagrant-courtesy-of-modern-ie.aspx

Any plans to use these boxes directly?

I do not think, it makes ievms obsolete.

**Comment by savingschampion** [comment]
MS has stopped offering these images. they ran one lot as a test, and now the links are dead :(

**Comment by xdissent** [comment]
That was easy! ;-)

**Comment by ryneeverett** [comment]
They offer them now, though the considerations in #29 may still apply.
