### ISSUE TITLE
Windows 7 IE11 Virtual Box - CRC failed

### ISSUE THREAD

**Issue by FlashK5N3** [xdissent/ievms#240]
I receive an 'Unexpected end of archive' when extracting parts to install a VM. Got all 5 parts from modern.ie so is there one or two missing according to the error below?

---------------------------------
Packed data CRC failed in IE11 - Win7.ova
Unexpected end of archive

**Comment by xdissent** [comment]
Assuming legit corruption here. Let me know if otherwise
