### ISSUE TITLE
IE11 developer tools broken

### ISSUE THREAD

**Issue by thebrokencube** [xdissent/ievms#246]
Not sure if this is the right place for this, but the IE11 developer tools are broken atm. This is a known bug on Microsoft's part ([see this link](http://answers.microsoft.com/en-us/ie/forum/ie11-windows_7/imposible-use-f12-developer-tools-exception-in/09b4f305-e436-4615-a8a5-705b0bc85bbd)),  so probably nothing needs changing for the project, though it could be possible to use a previous snapshot where it works instead.

**Comment by hulet** [comment]
Installing [Cumulative Security Update for Internet Explorer 11 for Windows 7 (KB3008923)](http://www.microsoft.com/en-us/download/details.aspx?id=45134) got the Developer Tools working again for me.

**Comment by toabi** [comment]
Jep, KB3008923 helps. Thank you.

**Comment by psema4** [comment]
Might be patched now... Just downloaded the images a couple days ago; figuring this should be the first thing to do after opening IE11 I tried to install the patch and got a message saying the update was not applicable to my computer. Sure enough, dev tools appears to be working out of the box.

**Comment by digitalmaster** [comment]
That did it!

**Comment by thebrokencube** [comment]
I tried reinstalling everything and it didn't seem to have the updated applied. However, manually installing the update works perfectly, thanks @hulet et. al.!

**Comment by grayghostvisuals** [comment]
Curious if this is the same issue captured in the following screenshot? The DevTools for IE11 VMs on a fresh download for Yosemite appears to be broken.

![screen shot 2015-08-18 at 7 30 16 pm](https://cloud.githubusercontent.com/assets/934322/9345501/a98ade7c-45df-11e5-82ec-a3239565566d.png)
