### ISSUE TITLE
Installation fails due to download failure

### ISSUE THREAD

**Issue by perqa** [xdissent/ievms#249]
Every time I have tried to install IE according to the instructions, the download fails with the following error messages. The internet connection is working well for other things at least (10Mbps, fiber).
```
curl: (56) Recv failure: Connection reset by peer

ERROR: Failed to download http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE9_Win7.zip to /Users/perqa/.ievms/IE9_Win7.zip using 'curl', error code (56)
```
OSX 10.10.2 

This might be a general problem with curl on OSX; I have now experienced the same problem on different local and remote networks as well (downloading other software).

**Comment by xdissent** [comment]
Haven't seen this before. I strongly suspect an good old fashioned networking issue, possibly just something local to your machine. Let me know if you still experience issues and we'll dig deeper.

**Comment by mrflix** [comment]
Got the same error on OSX 10.11 El Capitan.
![screen shot 2015-10-15 at 11 52 48](https://cloud.githubusercontent.com/assets/60777/10510435/4bd47ed8-7333-11e5-93c7-fce414451f34.png)
Worked like a charm last time.
