### ISSUE TITLE
Make a Torrent file available to download the whole set of images

### ISSUE THREAD

**Issue by eksperimental** [xdissent/ievms#250]
I have been struggling trying to download the whole set of images,
It's extremely slow and sometimes the connection resets
wouldn't it be better to have the whole set uploaded to bittorrent with instructions to place it in the ${HOME}/.ievms/ folder
that way people can choose (via bittorrent client) which ones to download if they are only interested in some...
and my files are still downloading.......

**Comment by noderat** [comment]
I imagine there are licencing issues with this, as the images can only be downloaded from microsoft's servers.

**Comment by xdissent** [comment]
Licensing! That's why I'm not self-hosting custom stripped-down versions of the VMs as well. =)
