### ISSUE TITLE
reduce size of Virtual Size for VMDK

### ISSUE THREAD

**Issue by AndrewLMacrae** [xdissent/ievms#253]
The standard scripts produce VMDKS with an actual size of about 10GB and a Virtual Size of 126 GB. Why is this so high? I ran two VMs on my MacBook with 256 GB drive - and filled and choked the drive.
Doesn't appear to be any way to reduce the virtual size of an existing VMDK (as opposed to when creating a new one). Any options here?

**Comment by xdissent** [comment]
**Practically** no. The size is set when the image is created (by MS). It **can** be changed with `VBoxManage`, but it doesn't change any partition information on the disk. We'd have to do all kinds of gymnastics to resize the partitions to make Windows happy. It also doesn't work with images that use snapshots apparently. But anyway, it *is* a dynamic virtual disk, shrinking and growing with your actual disk usage, which for most people is fine. I believe this is still applicable if you'd like to resize the disk yourself: https://forums.virtualbox.org/viewtopic.php?f=35&t=50661
