### ISSUE TITLE
ie devtools remote debug adapter

### ISSUE THREAD

**Issue by jasonkarns** [xdissent/ievms#255]
It would be awesome to include the IE11 remote debug adapter by default on IE11 vms

https://github.com/Microsoft/IEDiagnosticsAdapter

**Comment by xdissent** [comment]
I appreciate the idea, but I'm trying to stay away from installing things in the VMs. I considered adding Selenium IEDriver at one point (a very common use-case), but realized it would tie ievms to a particular version of Selenium that I'd have to keep up to date. Same thing here. That's part of the impetus behind [iectrl](https://github.com/xdissent/iectrl) - to make installing extras easy so we don't have to have them in ievms.
