### ISSUE TITLE
Error: VERR_NO_MEMORY

### ISSUE THREAD

**Issue by Math3v** [xdissent/ievms#257]
Hi there,

I have Ubuntu 14.04 running on older laptop with 4GB RAM. 
I wanted to install IE11 with command
`curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="11" bash`

and the result

Checking for VirtualBox
Checking for Oracle VM VirtualBox Extension Pack
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Building IE11 VM
Checking for existing OVA at /home/matej/.ievms/IE9 - Win7.ova
Checking for existing IE11 - Win7 VM
Creating IE11 - Win7 VM (disk: /home/matej/.ievms/IE11 - Win7-disk1.vmdk)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/matej/.ievms/IE9 - Win7.ova...
OK.
Disks:  vmdisk1	135291469824	-1	http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized	IE9 - Win7-disk1.vmdk	-1	-1	
Virtual system 0:
 0: Suggested OS type: "Windows7"
    (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
 1: VM name specified with --vmname: "IE11 - Win7"
 2: Number of CPUs: 2
    (change with "--vsys 0 --cpus <n>")
 3: Guest memory: 1024 MB
    (change with "--vsys 0 --memory <MB>")
 4: Sound card (appliance expects "", can change on import)
    (disable with "--vsys 0 --unit 4 --ignore")
 5: USB controller
    (disable with "--vsys 0 --unit 5 --ignore")
 6: Network adapter: orig NAT, config 3, extra slot=0;type=NAT
 7: CD-ROM
    (disable with "--vsys 0 --unit 7 --ignore")
 8: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 8 --ignore")
 9: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 9 --ignore")
10: SATA controller, type AHCI
    (disable with "--vsys 0 --unit 10 --ignore")
11: Hard disk image: source image=IE9 - Win7-disk1.vmdk, target path=/home/matej/.ievms/IE11 - Win7-disk1.vmdk, controller=10;channel=0
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not open the medium storage unit 'IE9 - Win7-disk1.vmdk'.
VBoxManage: error: VD: error VERR_NO_MEMORY opening image file 'IE9 - Win7-disk1.vmdk' (VERR_NO_MEMORY)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp

Does anybody have a similar problem?
Thank you.

**Comment by flosell** [comment]
I had the same issue, it was gone after rebooting. I guess there just wasn't enough memory available...

**Comment by xdissent** [comment]
Sorry guys, not sure what can be done about this. Shut down any other VMs or memory hungry processes and try again.

**Comment by gsaslis** [comment]
FWIW - extracting the .ovf (and .vmdk) and then using the .ovf filename (instead of the .ova), solved this issue for me, *without* needing to reboot! ;)
