### ISSUE TITLE
Windows 10, IE Edge

### ISSUE THREAD

**Issue by Munter** [xdissent/ievms#263]
Now that Windows 10 is available it would be very valuable to be able to easily install in to test bugs etc.

Is anyone already working on getting an ievms Windows 10 image up and running?

I can put in some work and send a PR, but I haven't touched this projects source code before, so I might need some guidance

**Comment by miquelfire** [comment]
The images used by this tool is download from [here](http://dev.modern.ie/tools/vms/linux/) (actually, I think I saw it using the mac version, not the Linux version I linked) which doesn't have a Windows 10 image.

Currently, only [this tool](https://remote.modern.ie/) can be used to test with Edge. Seeing as that page still using text about it being the tech preview version of Windows 10 (Matter of fact, it was never updated to talk about Edge it seems...) I doubt Microsoft had a chance to update that site to reflect the new Windows 10 yet.

**Comment by Munter** [comment]
I've also been asking MS devrel people for when Win10 will be available on modern.ie. But I know there is a dvd iso available for download. I guess that one needs a serial key to work at all though

**Comment by patrickkettner** [comment]
they're up now :]

**Comment by grayghostvisuals** [comment]
@Munter @xdissent Edge is now avail. here just as Patrick said \o/  [http://dev.modern.ie/tools/vms/windows](http://dev.modern.ie/tools/vms/windows)

**Comment by xdissent** [comment]
Fixed in `v0.3.0`

**Comment by Munter** [comment]
That was quick. Thank you so much for all the good work

**Comment by grayghostvisuals** [comment]
Cheers!
