### ISSUE TITLE
Edge fails to install

### ISSUE THREAD

**Issue by geoffyuen** [xdissent/ievms#272]
My platform: OSX Mavericks, Virtualbox 4.2.10 (the latest)

Downloads ok. Unzips ok, but then gives the following output:

    VBoxManage: error: 'Windows10_64' is not a valid Guest OS type
    VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component VirtualBox, interface IVirtualBox, callee IAppliance
    VBoxManage: error: Context: "Interpret" at line 330 of file VBoxManageAppliance.cpp

**Comment by xdissent** [comment]
VirtualBox 5.0 is required

**Comment by geoffyuen** [comment]
I guess I shouldn't depend on the Check Updates menu item. Thanks.
