### ISSUE TITLE
how to remove (instructions)

### ISSUE THREAD

**Issue by cordoval** [xdissent/ievms#277]
the readme lacks instructions for removal

sorry if this is a stupid request, but it would be a nice to have. Thanks!

**Comment by Jamesking56** [comment]
Just delete them from VirtualBox?

**Comment by cordoval** [comment]
manually? hmm , the installation is easy on cli, perhaps you should consider a cli to uninstall? anyway thanks and closing

**Comment by hkirsman** [comment]
I don't have anything in Virtualbox but I've found .ievms in the root of my user folder. I'll delete that also because it's taking over 7gb.
