### ISSUE TITLE
Syntax Error: Unknown sub command 'run' specified!

### ISSUE THREAD

**Issue by calebmeyer** [xdissent/ievms#278]
I ran the first bash command on the README. I'm on Mac OS X Yosemite, and I have VirtualBox version 4.3.30r101610 with the extension pack (same version). As of today (Fri Oct 2, 2015), this appears to be the latest version available.

Full output: http://pastebin.com/B67urBDt

This appears to have created and started the IE6 vm, despite the error.

**Comment by miquelfire** [comment]
Need VirtualBox 5 not 4 installed.

**Comment by calebmeyer** [comment]
That was my problem! Thank you!
