### ISSUE TITLE
Curling IE8 VM pulls in IE6.

### ISSUE THREAD

**Issue by marklreyes** [xdissent/ievms#284]
Curling a specific version of MSIE-8, but it's pulling in IE6.

```$ curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | IEVMS_VERSIONS="8" bash```
```Checking for VirtualBox```
```Checking for Oracle VM VirtualBox Extension Pack```
```Pack no. 0:   Oracle VM VirtualBox Extension Pack```
```Building IE 8 VM```
```Checking for existing OVA at /Users/reyesm/.ievms/IE6 - WinXP.ova```
```Downloading OVA ZIP from http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip to IE6_WinXP.zip (attempt 1 of 3)```

**Comment by npup** [comment]
Same thing here, only that I'm trying to get the IE7 image

**Comment by axnd** [comment]
AFAIK this is by design, it's grabbing the IE6 Windows XP VM first, then it downloads and installs IE 8. Windows XP VM image is reused for IE 6, 7, and 8.

**Comment by npup** [comment]
@axnd sure, if it produced a working IEx image afterwards, no problem. but the proposed line `curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="7" bash` does not currently do this.

**Comment by demersdesigns** [comment]
For what it's worth, the installation of IE 8 appeared to hang for me as part of the command line upgrade process, but running the IE 8 installer on the desktop of the VM worked fine.

**Comment by marklreyes** [comment]
If anyone still needs the IE8 VM specifically, modern.ie is another alternative,
https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

Virtual machine: IE8 on Win7

Select platform: Virtualbox
