### ISSUE TITLE
IE versions not installing. I always end up with version 9.

### ISSUE THREAD

**Issue by nextgenthemes** [xdissent/ievms#311]
The images are being created correctly but I always end up with IE9 installed. I tryed `"9 10 11"`

Also tried to upgrade IE, official download on M$ site does not work, maybe that the issue? Are they preventing this on purpose now to push Edge?

**Comment by nextgenthemes** [comment]
This is funny, I needed to download firefox to then download IE 11 from the officiall M$ site. In IE 9 the download wont start ;)

**Comment by xdissent** [comment]
I think this was related to an expired driver signing cert in the win7 image and should be fixed in 0.3.2. Please reopen if the problem persists!
