### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Jamesking56** [xdissent/ievms#313]
Hello,

This is more directly to @xdissent more than anything. Are you still maintaining this project?

If not, I'd love to write my own project that does the same thing as this but makes it work for Windows and Mac (.sh and .bat) with the URLs stored server-side so that I can update them without the need for users to update the project.

Of course, my version would be open source.

Cheers.

**Comment by stevenirby** [comment]
@Jamesking56 that would be really great if you did!

**Comment by pkuczynski** [comment]
Let us know when it's done. I will happily give it a try :)

**Comment by Jamesking56** [comment]
Just an update. I've started working on this and its going great. Planning to release open source so everyone here can use it and benefit from it.

So far, I have working VMs and a proper custom gui to manage them so its almost there. I just need to ensure compatibility on Windows, Mac and Linux machines (I have all three so I can phyiscally test) and create the relevant installers too.

Still a bit of work to do but when I've got an Alpha I'll release the source so everyone can have a go :)

**Comment by stevenirby** [comment]
@Jamesking56 awesome! I'll happily help you test it out when it's ready.

**Comment by stevenirby** [comment]
@Jamesking56 any ETA when you could have something up? Maybe even a feature branch. I could really use this right now.

**Comment by Jamesking56** [comment]
No ETAs yet I'm juggling this and a couple of other projects. I'm using Electron to make a task tray app and using Vagrant and Virtualbox for the virtual machine creation.
So, hopefully no more command line!
Will be bundling for Windows (x64), Mac (x64) and Linux (.deb and .rpm)

**Comment by stevenirby** [comment]
Sounds amazing. Let us know if you need any help!

**Comment by xdissent** [comment]
Hey @Jamesking56 I just released 0.3.2 which should bring everything up to speed. Your project sounds cool, best of luck on that!
