### ISSUE TITLE
Can someone update this so it works?

### ISSUE THREAD

**Issue by appcoco** [xdissent/ievms#317]
This no longer works for me

curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | bash

I am getting several errors.

after three attempts this doesn't download:

http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip

then after I download the file and run it locally, changing it around, still nothing.... also 

Tryting to download just IE 10, and I get:

env: 10: No such file or directory
(23) Failed writing body

Is this no longer maintained?

Thanks,
-O

**Comment by tdwesten** [comment]
Here the same errors :( - Please merge the pull-requests

**Comment by w-site** [comment]
Got the same error, pls fix

**Comment by Esaron** [comment]
https://github.com/esaron/ievms

Pull request: https://github.com/xdissent/ievms/pull/320

Keep in mind that I only added the hashes and tested for IE11 and Edge, and IE6 and IE7 are no longer available.  If you decide to use the fork and try to download IE8-IE10, please create update the hashes (They're marked with the string TODO because I'm lazy) and create a pull request.  Once the hashes are updated, I think the other versions will start working.

**Comment by Esaron** [comment]
Apparently IE 6 and 7 are still available but I doubt I will end up fixing thise ones.  Who knows though, maybe I'll get bored.

**Comment by appcoco** [comment]
esaron your link gets an error too

**Comment by Esaron** [comment]
Like I said, I only needed IE11 and Edge, so those are the only ones I tested for.  I will fix at least IE8+, but I won't have time for it for a while. If you just run the ievms.sh script, it won't work. You can set the environment variable to only grab 11 and Edge as it says in the readme if you want either of those.

**Comment by Esaron** [comment]
Well my plans today fell through, so I fixed IE8+.  The pull request is the same.

Here's what the fork can do:
IE8 - Win7
IE9 - Win7
IE10 - Win7
IE11 - Win7 (Win8.1 if you set REUSE_WIN7="no")
MSEdge - Win10

You can run the default command (curl -s https://raw.githubusercontent.com/esaron/ievms/master/ievms.sh | bash), and IE8-11 with Win7 and MSEdge with Win10 will be installed.  I may track down the old WinXP IE 6 and 7 vms and add them back in, but for now, this should suffice for almost everyone.  I only tested with VirtualBox 5.1 for Mac, so create an issue on the fork if you have any problems with the script on another platform, or if you find something that doesn't work that I forgot to test.

**Comment by appcoco** [comment]
Wohoo.. seems to be working!

Thanks, I will jump back if I get any errors.

**Comment by appcoco** [comment]
esaron, ty!
