### ISSUE TITLE
Currently does not work at all

### ISSUE THREAD

**Issue by Esaron** [xdissent/ievms#321]
Please merge https://github.com/xdissent/ievms/pull/322 so that this repository works again.

Be aware that support for WinXP vms, IE6, and IE7 has been removed.

Until the repo is fixed, you can use https://github.com/Esaron/ievms and the directions in the README there for IE8, IE9, IE10, IE11, and MSEdge.

**Comment by jrauh** [comment]
Thanks. This is one is working for me

**Comment by chrisspen** [comment]
This only partially works for me. The VM download succeeds, but after each one, it appears to try and download the guest additions, which fails due to a bad md5 check. I re-ran it several times, and it failed every time.

    Found VirtualBox Guest Additions ISO at /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso - skipping download
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Check failed - redownloading VirtualBox Guest Additions ISO
    Downloading VirtualBox Guest Additions ISO from http://download.virtualbox.org/virtualbox/5.0.24/VBoxGuestAdditions_5.0.24.iso to /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (attempt 1 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 55.5M  100 55.5M    0     0  6874k      0  0:00:08  0:00:08 --:--:-- 7275k
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Redownloading VirtualBox Guest Additions ISO
    Found VirtualBox Guest Additions ISO at /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso - skipping download
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Check failed - redownloading VirtualBox Guest Additions ISO
    Downloading VirtualBox Guest Additions ISO from http://download.virtualbox.org/virtualbox/5.0.24/VBoxGuestAdditions_5.0.24.iso to /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (attempt 2 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 55.5M  100 55.5M    0     0  6661k      0  0:00:08  0:00:08 --:--:-- 7077k
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Redownloading VirtualBox Guest Additions ISO
    Found VirtualBox Guest Additions ISO at /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso - skipping download
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Check failed - redownloading VirtualBox Guest Additions ISO
    Downloading VirtualBox Guest Additions ISO from http://download.virtualbox.org/virtualbox/5.0.24/VBoxGuestAdditions_5.0.24.iso to /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (attempt 3 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 55.5M  100 55.5M    0     0  7149k      0  0:00:07  0:00:07 --:--:-- 7258k
    MD5 check failed for /home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (wanted 8cf1af35478905ea29828954ddb2c5ee, got ec279e80835a4dbb63d3d65baf23ccf2)
    Failed to download http://download.virtualbox.org/virtualbox/5.0.24/VBoxGuestAdditions_5.0.24.iso to /home/chris/.ievms//home/chris/.ievms/VBoxGuestAdditions_5.0.24.iso (attempt 3 of 3)

**Comment by xdissent** [comment]
I just released 0.3.2 that fixes all the URLs and uses the same images. Please reopen if that doesn't work for you.
