### ISSUE TITLE
Control ISO is failing to download

### ISSUE THREAD

**Issue by noldona** [xdissent/ievms#326]
The script is attempting to download the control iso and fails all 3 times. Attempting to go to the path manually is returning a page with a messaging saying the file isn't found. This like likely due to Dropbox's recent change where public folders are no longer public.

**Comment by xdissent** [comment]
Yep, totally dropbox. They also don't seem to have a way to get a permanent direct dl url anymore, so I switched to GitHub release binaries for the iso. Sorry about that! Fixed in 0.3.3
