### ISSUE TITLE
Cannot install VirtualBox Extension Pack on Ubuntu

### ISSUE THREAD

**Issue by jamesottaway** [xdissent/ievms#9]
I ran the script and it downloaded Oracle_VM_VirtualBox_Extension_Pack-4.1.2-73507.vbox-extpack to ~/.ievms and tried to install it.

The command failed with:

```
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to install "/home/james/.ievms/Oracle_VM_VirtualBox_Extension_Pack-4.1.2-73507.vbox-extpack": The installer failed with exit code 1:
VBoxExtPackHelperApp: error: The group is not a system group and it has write access to '/usr'
```

The same happens if I use the VirtualBox GUI to install the same extpack. I'm running Ubuntu 11.04.

**Comment by liviubalan** [comment]
Good topicl! If you want a video tutorial on how to install VirtualBox Extension Pack (on Linux Mint/Ubuntu) you can see http://www.liviubalan.com/install-virtualbox-extension-pack
